# Note:
# Players who are not opped require permissions:
# To use the plugin: minigame.all
#

#This controls whether or not you want the plugin to be enabled
Enabled: true

#
#
# This section is for manhunt
#
#

#This controls how long the grace time will be set for.
ManhuntGraceTimer: 60

# This controls how far runners can be before the hunter is allowed to teleport closer to them
ManhuntTeleportDistance: 400

#This controls how far away the border should be from the stronghold
ManhuntBorderDistance: 500

#
#
# This section is for deathswap
#
#

DeathSwapTimer: 300

#
#
# This section is for blockhunt
#
#

#This controls the items used by the block hunt minigame.
#By default it uses items from 1.17, but you can change the items to make it compatible with earlier versions of minecraft
BlocksRolled:
  Easy:
    - GRASS_BLOCK
    - DIRT
    - SAND
    - BIRCH_LOG
    - BIRCH_PLANKS
    - SPRUCE_LOG
    - SPRUCE_PLANKS
    - OAK_LOG
    - OAK_PLANKS
    - SANDSTONE
    - SANDSTONE_STAIRS
    - SANDSTONE_WALL
    - BIRCH_LEAVES
    - SPRUCE_LEAVES
    - OAK_LEAVES
    - COBBLESTONE
    - STONE
    - GLASS
    - ANDESITE
    - COAL_BLOCK
    - COAL_ORE
    - IRON_ORE
    - IRON_BLOCK
    - DIORITE
    - GRANITE
    - CACTUS
    - COPPER_ORE
    - DEEPSLATE
    - HAY_BLOCK
    - TERRACOTTA
    - GRAVEL
    - SNOW_BLOCK
    - YELLOW_WOOL
    - BEDROCK
    - PUMPKIN
    - COMPOSTER
    - STRIPPED_BIRCH_LOG
    - STRIPPED_SPRUCE_LOG
    - STRIPPED_OAK_LOG
    - RED_WOOL
    - BLUE_WOOL
    - ORANGE_WOOL
    - PURPLE_WOOL
  Medium:
    - MOSSY_COBBLESTONE
    - BOOKSHELF
    - CAULDRON
    - QUARTZ_BLOCK
    - SOUL_SOIL
    - TNT
    - LECTERN
    - COPPER_BLOCK
    - BREWING_STAND
    - NETHER_BRICKS
    - NETHERRACK
    - SOUL_SAND
    - CRYING_OBSIDIAN
    - BLACKSTONE
    - GILDED_BLACKSTONE
    - GLOWSTONE
    - RESPAWN_ANCHOR
    - NETHER_GOLD_ORE
    - NETHER_WART_BLOCK
    - SHROOMLIGHT
    - MAGMA_BLOCK
    - WARPED_WART_BLOCK
    - POLISHED_BLACKSTONE
    - DAYLIGHT_DETECTOR
    - SMITHING_TABLE
    - SMOOTH_BASALT
    - BASALT
    - DETECTOR_RAIL
    - MOSS_BLOCK
    - DRIPSTONE_BLOCK
    - STRIPPED_WARPED_STEM
    - STRIPPED_CRIMSON_STEM
    - CRIMSON_STEM
    - WARPED_STEM
    - OBSIDIAN
    - LANTERN
    - NOTE_BLOCK
  Hard:
    - SEA_LANTERN
    - SEA_PICKLE
    - END_PORTAL_FRAME
    - ROOTED_DIRT
    - SPONGE
    - JUKEBOX
    - RAW_GOLD_BLOCK
    - PRISMARINE
    - PODZOL
    - PURPUR_BLOCK
    - PURPUR_SLAB
    - ANCIENT_DEBRIS
    - END_STONE
    - DRAGON_EGG
    - END_ROD
    - CANDLE
    - DIAMOND_BLOCK
    - END_STONE_BRICKS
    - END_STONE_BRICK_WALL
    - ENDER_CHEST
    - SHULKER_BOX
    - TINTED_GLASS
    - CHORUS_FLOWER
    - SLIME_BLOCK
    - POWERED_RAIL
    - ANVIL
    - BLUE_ICE
    - MYCELIUM
    - BLAST_FURNACE
    - AMETHYST_BLOCK
    - MELON
    - LILY_PAD
    - LIGHTNING_ROD
    - BELL
    - CAMPFIRE
    - SOUL_CAMPFIRE



#This controls the difficulty of the game block hunt. The number demonstrates how many times block hunt will roll until it switches to a higher difficulty
BlockHuntDifficulty: 20

#This controls how long the players will have to find their assigned block. The unit used is seconds
BlockHuntTime: 300

#This controls whether or not the timer will finish even all players have gotten their blocks,
# or if it will keep going until the end of the timer
#True means players can end the timer prematurely
PlayersCanFinishTimer: true


